version: '1'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "finex_etf_calc_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "finex_etf_calc"
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672