APP_NAME: finex_etf_calc

INIT_LOGGING: false
DEBUG: true
LOG_LEVEL: DEBUG

SWAGGER_URL: ''

DB_PG_NAME: postgres
DB_SCHEMA: finex_etf_calc_db
DB_NAME: finex_etf_calc_db

DB_PG_USERNAME: postgres
DB_PG_PASSWORD: finex_etf_calc
DB_PG_HOST: localhost
DB_PG_PORT: 5432