APP_NAME: finex_etf_calc

DB_PG_NAME: postgres
DB_SCHEMA: finex_etf_calc_db
DB_NAME: finex_etf_calc_db

DB_PG_USERNAME: postgres
DB_PG_PASSWORD: finex_etf_calc
DB_PG_HOST: localhost
DB_PG_PORT: 5432

FINEX_PRICE_ON_DAY_URL: 'https://some-url.ru'
FINEX_PRICE_HISTORY_URL: 'https://some-url.ru'
CBR_URL: 'https://some-url.ru'

RABBITMQ_URLS:
  - amqp://admin:admin@127.0.0.1:5672