"""initial

Revision ID: 764f9278f210
Revises: 
Create Date: 2023-12-10 18:56:41.917028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from finex_etf_calc.app.config import config

# revision identifiers, used by Alembic.
revision: str = '764f9278f210'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tcurrencies',
    sa.Column('name', sa.String(length=3), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='finex_etf_calc_db'
    )
    op.create_table('ttypes_deal',
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='finex_etf_calc_db'
    )
    op.create_table('tfunds',
    sa.Column('ticker', sa.String(length=4), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('currencies_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['currencies_id'], ['finex_etf_calc_db.tcurrencies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='finex_etf_calc_db'
    )
    op.create_table('tprices_currency',
    sa.Column('currencies_id', sa.Integer(), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['currencies_id'], ['finex_etf_calc_db.tcurrencies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='finex_etf_calc_db'
    )
    op.create_table('tdeals',
    sa.Column('funds_id', sa.Integer(), nullable=False),
    sa.Column('type_deal_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('date_deal', sa.Date(), nullable=False),
    sa.Column('count', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['funds_id'], ['finex_etf_calc_db.tfunds.id'], ),
    sa.ForeignKeyConstraint(['type_deal_id'], ['finex_etf_calc_db.ttypes_deal.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='finex_etf_calc_db'
    )
    op.create_table('tprices_fund',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['finex_etf_calc_db.tfunds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='finex_etf_calc_db'
    )
    # ### end Alembic commands ###
    meta = sa.MetaData()
    ttypes_deal = sa.Table(
        'ttypes_deal',
        meta,
        sa.Column('name', sa.String),
        sa.Column('description', sa.String),
        sa.Column('id', sa.Integer),
        schema=config['DB_SCHEMA']
    )
    op.bulk_insert(
        ttypes_deal,
        [
            {
                'name': 'buy',
                'description': 'Покупка'
            },
            {
                'name': 'sell',
                'description': 'Продажа'
            }
        ]
    )
    tcurrencies = sa.Table(
        'tcurrencies',
        meta,
        sa.Column('name', sa.String),
        sa.Column('code', sa.Integer),
        sa.Column('description', sa.String),
        sa.Column('id', sa.Integer),
        schema=config['DB_SCHEMA']
    )
    op.bulk_insert(
        tcurrencies,
        [
            {
                'name': 'USD',
                'code': 840,
                'description': 'Доллар США'
            },
            {
                'name': 'RUB',
                'code': 643,
                'description': 'Российский рубль'
            },
            {
                'name': 'KZT',
                'code': 398,
                'description': 'Тенге'
            },
            {
                'name': 'EUR',
                'code': 978,
                'description': 'Евро'
            }
        ]
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tprices_fund', schema='finex_etf_calc_db')
    op.drop_table('tdeals', schema='finex_etf_calc_db')
    op.drop_table('tprices_currency', schema='finex_etf_calc_db')
    op.drop_table('tfunds', schema='finex_etf_calc_db')
    op.drop_table('ttypes_deal', schema='finex_etf_calc_db')
    op.drop_table('tcurrencies', schema='finex_etf_calc_db')
    # ### end Alembic commands ###
