"""initial

Revision ID: 94396a120fae
Revises: 
Create Date: 2023-12-05 21:04:15.820011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94396a120fae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tfunds',
    sa.Column('ticker', sa.String(length=4), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='finex_etf_calc_db'
    )
    op.create_table('tcurrencies',
    sa.Column('name', sa.String(length=3), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('funds_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['funds_id'], ['finex_etf_calc_db.tfunds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='finex_etf_calc_db'
    )
    op.create_table('tdeals',
    sa.Column('funds_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('deal_date', sa.Date(), nullable=False),
    sa.Column('count', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['funds_id'], ['finex_etf_calc_db.tfunds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='finex_etf_calc_db'
    )
    op.create_table('tprices_fund',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['finex_etf_calc_db.tfunds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='finex_etf_calc_db'
    )
    op.create_table('tprices_currency',
    sa.Column('currencies_id', sa.Integer(), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['currencies_id'], ['finex_etf_calc_db.tcurrencies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='finex_etf_calc_db'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tprices_currency', schema='finex_etf_calc_db')
    op.drop_table('tprices_fund', schema='finex_etf_calc_db')
    op.drop_table('tdeals', schema='finex_etf_calc_db')
    op.drop_table('tcurrencies', schema='finex_etf_calc_db')
    op.drop_table('tfunds', schema='finex_etf_calc_db')
    # ### end Alembic commands ###
